eveg_app:
    resource: "@evegAppBundle/Resources/config/routing/routing.yml"
    type: be_simple_i18n

eveg_admin:
    resource: "@evegAppBundle/Resources/config/routing/routing_admin.yml"
    prefix: /admin

eveg_user:
    resource: "@evegAppBundle/Resources/config/routing/routing_user.yml"
    prefix: /user

# -------------
# FOSRestBundle
# -------------
rest:
    type: rest
    resource: "@evegAppBundle/Resources/config/routing/routing_rest.yml"
    prefix: /api

# -------------
# FOSUserBundle
# -------------
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# -------------
# FOSJsRouting
# -------------
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# -------------
# EsayAdminBundle
# -------------
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /easy-admin

# -------------
# LiipImagineBundle
# -------------
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"